name: Coverity POC with GitHub-hosted runner
on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: synopsys-sig-community/synopsys-github-templates/coverity@v0.0.2-poc
        with:
          coverity-url: ${{ secrets.COVERITY_URL }}
          coverity-user: ${{ secrets.COVERITY_USER }}
          coverity-passphrase: ${{ secrets.COVERITY_PASSPHRASE }}

          #coverity-download-url: https://github.com/synopsys-sig-community/synopsys-github-templates/releases/download/v0.0.1
          coverity-download-url: https://github.com/synopsys-sig-community/synopsys-github-bits/releases/download/v2021.12.1
          coverity-download-version: 2021.12.1
          coverity-download-creds: ${{ secrets.COVERITY_DOWNLOAD_CREDS }}
          coverity-license-url: https://thirteen.community/private/license.dat
          coverity-license-creds: ${{ secrets.COVERITY_LICENSE_CREDS }}

          coverity-project-name: ${{ github.event.repository.name }}
          build-command: mvn package
          coverity-checker-options: --webapp-security
          create-stream-and-project: true
          security-gate-view-name: "High and Medium Severity"
          github-token: ${{ secrets.GITHUB_TOKEN }}
