name: Coverity POC with GitHub-hosted runner
on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: synopsys-sig-community/synopsys-github-templates/coverity@v0.0.2-poc
        with:
          coverity-url: ${{ secrets.COVERITY_URL }}
          coverity-user: ${{ secrets.COVERITY_USER }}
          coverity-passphrase: ${{ secrets.COVERITY_PASSPHRASE }}

          coverity-download-url: https://github.com/synopsys-sig-community/synopsys-github-templates/releases/download/v0.0.1
          coverity-download-version: 2021.12.1
          coverity-download-creds: ${{ secrets.COVERITY_DOWNLOAD_CREDS }}
          coverity-license-url: https://thirteen.community/private/license.dat
          coverity-license-creds: ${{ secrets.COVERITY_LICENSE_CREDS }}

          coverity-project-name: ${{ github.event.repository.name }}
          coverity-checker-options: --webapp-security

          # Make sure to give "Project Admin" and "Stream Admin" rights to your
          # COVERITY_USER in Coverity Connect before enabling this feature.
          create-stream-and-project: true
          # Make sure to create a saved view of this name and test it interatcively
          # in Coverity Connect before enabling this feature.
          security-gate-view-name: "High and Medium Severity"
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: analysis-log
        path: idir/output/analysis-log.txt

